jdbc.url=jdbc:trino://trino:8080/semantic_demo/ice_db
jdbc.driver=io.trino.jdbc.TrinoDriver
jdbc.user=admin
jdbc.password=
ontop.ontologyFile=/opt/ontop/input/tpch.owl
ontop.mappingFile=/opt/ontop/input/tpch.obda
ontop.propertiesFile=/opt/ontop/input/ontop.properties
