#single node install config
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080
catalog.management=${ENV:CATALOG_MANAGEMENT}
http-server.authentication.type=PASSWORD
internal-communication.shared-secret=lvy9v7NWnRiGAlyWePMaCjNVJ5qTq9+bb5hpfeqgYaeYjC22GUd7ym9YLN8ov2pPU5lr9RY6EJES8yQm0oPCcH8t3NyiY+x255du9fXLCFpcg0cjch5gZZ0qtVBSDFoaqOPRxNeK/W9SRi2xqu5wUfSCBy4K1e45PP8NMeLbL/wK6g8xfHC9CeUthMqQPzx6HtfDA1U4WSMVsARgNmXgo+1yQKQTu8XwJqfExxornEvj1sd6F6rTvXQntGBBECNEVFzM2n0QbNzEEn/8NiDJJjSlItxDM3HcJFr2jrd+G/2bXXONxi9+mFPkt8jpJtayMbIl/dcxEd107p1StuipeOfnd21l1A3CEwRNBXC7ey9oWmo+mPX0RYEfB33UVR3ajyjpdsGR9vMJWmsFxBWatb/oCuFRH6R9tLCeN/rztHtqC5Q+xGbe83cj6PaY3xI4HSBOkSrU498ktrkPtTpxvF1ZIBvgWv9kCFH5FDd7WCEFTKHZ/nsP8GZdaeD4VVsp8z2+94bjMKWEW0cG94ooujnD73ZFRAU1MGmktThUljQn5OQ19Li8bHK5hjChWi+/l/pMGJnPYbpK9xng1nlBN/sNvgwPtk35gqDQFfGK3mfqC+BzB00xSNMlhGQhDqL7UWB8pO8v1wvURvEExIrqpmmyf4+CE19ViD+ScizCMNw=
