spring.main.web-application-type=none

# NOTE: Disable banner and console logging for STDIO MCP transport
spring.main.banner-mode=off
logging.pattern.console=

spring.ai.mcp.server.name=datalakehouse-mcp
spring.ai.mcp.server.version=0.1.0

logging.file.name=~/lakehouse-mcp.log

trino.host=localhost
trino.port=8080
trino.user=admin
trino.catalog=semantic_demo
trino.schema=ice_db
